use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let workspace_dir = PathBuf::from(&manifest_dir)
        .parent()
        .unwrap()
        .to_path_buf();
    let blog_ja_dir = workspace_dir.join("content/blog");
    let blog_en_dir = workspace_dir.join("content/blog/en");

    // Tell cargo to rerun when blog posts are added/removed
    println!("cargo:rerun-if-changed={}", blog_ja_dir.display());
    println!("cargo:rerun-if-changed={}", blog_en_dir.display());

    let ja_posts = collect_posts(&blog_ja_dir);
    let en_posts = collect_posts(&blog_en_dir);

    let mut code = String::new();

    code.push_str("/// Auto-generated by build.rs — do not edit manually.\n");
    code.push_str("/// Add .md files to content/blog/ (ja) or content/blog/en/ (en).\n\n");

    code.push_str("pub const POSTS_JA: &[(&str, &str)] = &[\n");
    for (slug, path) in &ja_posts {
        // include_str! with absolute path so it resolves from OUT_DIR
        code.push_str(&format!(
            "    ({slug:?}, include_str!({path:?})),\n",
            slug = slug,
            path = path.display()
        ));
        // Ensure cargo reruns when individual post files change
        println!("cargo:rerun-if-changed={}", path.display());
    }
    code.push_str("];\n\n");

    code.push_str("pub const POSTS_EN: &[(&str, &str)] = &[\n");
    for (slug, path) in &en_posts {
        code.push_str(&format!(
            "    ({slug:?}, include_str!({path:?})),\n",
            slug = slug,
            path = path.display()
        ));
        println!("cargo:rerun-if-changed={}", path.display());
    }
    code.push_str("];\n\n");

    code.push_str("/// Legacy alias for backward compatibility\n");
    code.push_str("pub const POSTS: &[(&str, &str)] = POSTS_JA;\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = PathBuf::from(&out_dir).join("blog_posts.rs");
    fs::write(&out_path, code).unwrap();
}

/// Collect .md files from `dir` (non-recursive), sorted newest-first by filename.
fn collect_posts(dir: &PathBuf) -> Vec<(String, PathBuf)> {
    if !dir.exists() {
        return vec![];
    }
    let mut posts: Vec<(String, PathBuf)> = fs::read_dir(dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| {
            let p = e.path();
            p.is_file() && p.extension().map(|x| x == "md").unwrap_or(false)
        })
        .map(|e| {
            let path = e.path().canonicalize().unwrap();
            let slug = path
                .file_stem()
                .unwrap()
                .to_string_lossy()
                .to_string();
            (slug, path)
        })
        .collect();

    // Sort descending by slug (filenames start with YYYY-MM-DD)
    posts.sort_by(|a, b| b.0.cmp(&a.0));
    posts
}
