use pulldown_cmark::{html::push_html, Options, Parser};

use crate::i18n::Locale;

pub struct PostMeta {
    pub title: String,
    pub date: String,
    pub tags: Vec<String>,
    pub description: String,
}

// POSTS_JA, POSTS_EN, POSTS — auto-generated by build.rs from content/blog/
// To add a post: create content/blog/YYYY-MM-DD-slug.md (ja) or content/blog/en/YYYY-MM-DD-slug.md (en)
// then rebuild. No manual editing needed here.
include!(concat!(env!("OUT_DIR"), "/blog_posts.rs"));

pub fn posts_for_locale(locale: Locale) -> &'static [(&'static str, &'static str)] {
    match locale {
        Locale::Ja => POSTS_JA,
        // All non-Japanese locales fall back to English blog posts
        _ => POSTS_EN,
    }
}

pub fn parse_frontmatter(raw: &str) -> (PostMeta, &str) {
    let content = raw.trim_start();
    if !content.starts_with("---") {
        return (
            PostMeta {
                title: String::new(),
                date: String::new(),
                tags: vec![],
                description: String::new(),
            },
            content,
        );
    }

    let after_first = &content[3..];
    let end = after_first.find("\n---").unwrap_or(after_first.len());
    let frontmatter = &after_first[..end];
    let body = if end < after_first.len() {
        &after_first[end + 4..]
    } else {
        ""
    };

    let mut title = String::new();
    let mut date = String::new();
    let mut tags = Vec::new();
    let mut description = String::new();

    for line in frontmatter.lines() {
        let line = line.trim();
        if let Some(val) = line.strip_prefix("title:") {
            title = val.trim().trim_matches('"').replace("\\\"", "\"");
        } else if let Some(val) = line.strip_prefix("date:") {
            date = val.trim().to_string();
        } else if let Some(val) = line.strip_prefix("description:") {
            description = val.trim().trim_matches('"').replace("\\\"", "\"");
        } else if let Some(val) = line.strip_prefix("tags:") {
            let val = val.trim();
            if val.starts_with('[') {
                tags = val
                    .trim_start_matches('[')
                    .trim_end_matches(']')
                    .split(',')
                    .map(|t| t.trim().trim_matches('"').trim_matches('\'').to_string())
                    .filter(|t| !t.is_empty())
                    .collect();
            }
        }
    }

    (PostMeta { title, date, tags, description }, body)
}

pub fn md_to_html(md: &str) -> String {
    let opts = Options::ENABLE_TABLES | Options::ENABLE_STRIKETHROUGH | Options::ENABLE_TASKLISTS;
    let parser = Parser::new_ext(md, opts);
    let mut html = String::new();
    push_html(&mut html, parser);
    html
}

pub fn reading_minutes(body: &str) -> usize {
    (body.chars().count() / 400).max(1)
}

pub fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
